import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Navigation from "@/components/nav-link";
import Navigation from "@/components/v2/nav-link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="w-full max-w-7xl mx-auto p-1">
          <Navigation />
          {children}
        </main>
      </body>
    </html>
  );
}
